import { supabase } from '../supabase';

export interface Cohort {
    id?: string;
    name: string;
    institution_id: string;
    course_id?: string;
    description?: string;
    invite_code?: string;
    is_active?: boolean;
    created_by: string;
    created_at?: string;
    updated_at?: string;
    // Computed fields from joins
    member_count?: number;
}

export interface CohortMember {
    cohort_id: string;
    user_id: string;
    joined_at?: string;
}

export class CohortService {
    /**
     * Create a new cohort. Invite code is auto-generated by DB trigger.
     */
    static async createCohort(
        name: string,
        institutionId: string,
        createdBy: string,
        courseId?: string,
        description?: string
    ): Promise<Cohort | null> {
        try {
            const { data, error } = await supabase
                .from('cohorts')
                .insert({
                    name,
                    institution_id: institutionId,
                    course_id: courseId || null,
                    description: description || null,
                    created_by: createdBy,
                })
                .select()
                .single();

            if (error) throw error;
            return data as Cohort;
        } catch (e) {
            console.error('CohortService: Create failed:', e);
            return null;
        }
    }

    /**
     * List all cohorts for an institution.
     */
    static async listCohorts(institutionId: string): Promise<Cohort[]> {
        try {
            const { data, error } = await supabase
                .from('cohorts')
                .select('*, cohort_members(count)')
                .eq('institution_id', institutionId)
                .order('created_at', { ascending: false });

            if (error) throw error;

            return (data || []).map((c: any) => ({
                ...c,
                member_count: c.cohort_members?.[0]?.count || 0,
            }));
        } catch (e) {
            console.error('CohortService: List failed:', e);
            return [];
        }
    }

    /**
     * Get a single cohort by ID.
     */
    static async getCohort(cohortId: string): Promise<Cohort | null> {
        try {
            const { data, error } = await supabase
                .from('cohorts')
                .select('*, cohort_members(count)')
                .eq('id', cohortId)
                .single();

            if (error) throw error;
            return {
                ...data,
                member_count: data.cohort_members?.[0]?.count || 0,
            } as Cohort;
        } catch (e) {
            console.error('CohortService: Get failed:', e);
            return null;
        }
    }

    /**
     * Find a cohort by invite code.
     */
    static async findByInviteCode(code: string): Promise<Cohort | null> {
        try {
            const { data, error } = await supabase
                .from('cohorts')
                .select('*')
                .eq('invite_code', code.toUpperCase())
                .eq('is_active', true)
                .single();

            if (error) throw error;
            return data as Cohort;
        } catch (e) {
            console.error('CohortService: Find by code failed:', e);
            return null;
        }
    }

    /**
     * Add students to a cohort (batch).
     */
    static async addStudents(cohortId: string, userIds: string[]): Promise<{ added: number; errors: string[] }> {
        const errors: string[] = [];
        let added = 0;

        for (const userId of userIds) {
            try {
                const { error } = await supabase
                    .from('cohort_members')
                    .insert({ cohort_id: cohortId, user_id: userId });

                if (error) {
                    if (error.code === '23505') {
                        // Duplicate — already a member
                        errors.push(`${userId}: already in cohort`);
                    } else {
                        throw error;
                    }
                } else {
                    added++;
                }
            } catch (e: any) {
                errors.push(`${userId}: ${e.message}`);
            }
        }

        return { added, errors };
    }

    /**
     * Remove a student from a cohort.
     */
    static async removeStudent(cohortId: string, userId: string): Promise<boolean> {
        try {
            const { error } = await supabase
                .from('cohort_members')
                .delete()
                .eq('cohort_id', cohortId)
                .eq('user_id', userId);

            if (error) throw error;
            return true;
        } catch (e) {
            console.error('CohortService: Remove student failed:', e);
            return false;
        }
    }

    /**
     * Get all members of a cohort.
     */
    static async getCohortMembers(cohortId: string): Promise<CohortMember[]> {
        try {
            const { data, error } = await supabase
                .from('cohort_members')
                .select('*')
                .eq('cohort_id', cohortId)
                .order('joined_at', { ascending: true });

            if (error) throw error;
            return (data || []) as CohortMember[];
        } catch (e) {
            console.error('CohortService: Get members failed:', e);
            return [];
        }
    }

    /**
     * Update a cohort (name, course, description).
     */
    static async updateCohort(
        cohortId: string,
        updates: Partial<Pick<Cohort, 'name' | 'course_id' | 'description' | 'is_active'>>
    ): Promise<boolean> {
        try {
            const { error } = await supabase
                .from('cohorts')
                .update({ ...updates, updated_at: new Date().toISOString() })
                .eq('id', cohortId);

            if (error) throw error;
            return true;
        } catch (e) {
            console.error('CohortService: Update failed:', e);
            return false;
        }
    }

    /**
     * Delete (archive) a cohort.
     */
    static async deleteCohort(cohortId: string): Promise<boolean> {
        try {
            const { error } = await supabase
                .from('cohorts')
                .update({ is_active: false, updated_at: new Date().toISOString() })
                .eq('id', cohortId);

            if (error) throw error;
            return true;
        } catch (e) {
            console.error('CohortService: Delete failed:', e);
            return false;
        }
    }
}
